### ISSUE TITLE
M1 mac build

### ISSUE THREAD

**Issue by jellohouse** [atom-community/atom#468]
## Summary

It would be great to have an m1 (arm64) version for mac.

## Motivation

I came from this issue on the original atom repo:
https://github.com/atom/atom/issues/23500

Thinking it would be here for m1 native.

## Describe alternatives you've considered

Using atom (intel) mac.

## Additional context

No additional context.

**Comment by icecream17** [comment]
I think this is a duplicate of https://github.com/atom-community/atom/issues/419 but let me know if it's not

**Comment by jellohouse** [comment]
Ohh yep my bad I didn't see that - thanks!
