### ISSUE TITLE
How is this progressing?

### ISSUE THREAD

**Issue by manngo** [atom-community/atom#483]
With 15 December fast approaching, I can’t get any information on whether Atom Community is on track to be a replacement. There are no official releases, and GitHub is looking pretty quiet at the moment.

The downloaded Atom Dev looks OK, though I have only just started trying it out. Is this a viable solution?

**Comment by joshcangit** [comment]
Still waiting for the CI to be fixed.

ATM, it looks like the nightly is still more stable than this.

**Comment by aminya** [comment]
See https://github.com/atom-community/atom/discussions/475#discussioncomment-3895279
